<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-04-12 17:11
=======
# Generated by Django 4.0.3 on 2022-04-19 10:39
>>>>>>> kart

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gib2Prosjekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolig',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
