# Generated by Django 4.0.3 on 2022-04-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gib2Prosjekt', '0002_bolig_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolig',
            name='area',
            field=models.IntegerField(default=155),
        ),
        migrations.AddField(
            model_name='bolig',
            name='bedroom',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bolig',
            name='energy',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='bolig',
            name='type',
            field=models.CharField(default='Enebolig', max_length=20),
        ),
    ]
