# Generated by Django 4.0.3 on 2022-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gib2Prosjekt', '0003_bolig_area_bolig_bedroom_bolig_energy_bolig_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolig',
            name='year',
            field=models.IntegerField(default=2012),
        ),
    ]
